# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  PACKAGE_S3_BUCKET_NAME : "myproject1-aplication-packages"
  APPLICATION_NAME       : "Myproject1"
  ENVIRONMENT_NAME       : "Myproject1-env"
  DEPLOY_PACKAGE_NAME    : "Myproject1_app_${{ github.sha }}.zip"
  AWS_REGION_NAME        : "eu-north-1"

on:
  push:
    branches: [ main ]
      
jobs:
  my-ci-part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2
      
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_SSH_HOST }}
          username: ${{ secrets.MY_SSH_USER }}
          key: ${{ secrets.MY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.MY_SSH_PORT }}
          script: |
            cp ./  /home/ubuntu/Myproject1_app_${{ github.sha }}/ -x *.git*
            docker build -t Myproject1_app_${{ github.sha }}:v.1 /home/ubuntu/Myproject1_app_${{ github.sha }}/
            docker run -d -p 7777:80 Myproject1_app_${{ github.sha }}:v1 
             
      - name: Print Message for CD finish
        run : echo "CD Pipeline part finished successfully!" 
    
          
          
          
