# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-Remote-server
env:
  APPLICATION_NAME       : "myproject1_${{ github.sha }}"
  
on:
  push:
    branches: [ main ]
      
jobs:
  my-ci-part:
    runs-on: ubuntu-latest

    steps:   
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_SSH_HOST }}
          username: ${{ secrets.MY_SSH_USER }}
          key: ${{ secrets.MY_SSH_PRIVATE_KEY }}
          port: ${{ secrets.MY_SSH_PORT }}
          script: |
            mkdir ${{ env.APPLICATION_NAME }}
            cd ${{ env.APPLICATION_NAME }}
            git clone git@github.com:Stat-Alex/myproject1.git myproject_application
            cd myproject_application
            docker build -t myproject_app_${{ github.sha }}:v.1 .
            docker stop $(docker ps -aq)
            docker rm $(docker ps -aq)
            docker run -d -p 7777:80 myproject_app_${{ github.sha }}:v.1 
             
      - name: Print Message for CD finish
        run : echo "CD Pipeline part finished successfully!!!" 
        
